//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCDatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocRecord
    {
        public int Id { get; set; }
    
        public virtual MedCard MedCard { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
